#! /bin/sh

# BSPWM CONFIG
bspc monitor -d I II III IV V

bspc config border_width 2
bspc config window_gap 6
bspc config split_ratio 0.52

bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config single_monocle true

# AUTOLOAD

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.screenlayout/screen.sh &
picom --experimental-backends &
$HOME/.config/polybar/launch.sh

