#! /bin/sh

# BSPWM CONFIG
bspc monitor -d   III IV V

bspc config border_width 2
bspc config window_gap 6
bspc config split_ratio 0.58

bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config single_monocle true

bspc config normal_border_color "#282828" 
bspc config focused_border_color "#68668f"

# AUTOLOAD

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.screenlayout/screen.sh &
nitrogen --set-scaled --random $HOME/.wallpaper/ &
picom --experimental-backends &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr

